// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tutorial.helloworld.proto

package tutorial;

public final class TutorialHelloworld {
  private TutorialHelloworld() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface helloworldOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tutorial.helloworld)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * ID
     * </pre>
     *
     * <code>required int32 id = 1;</code>
     * @return Whether the id field is set.
     */
    boolean hasId();
    /**
     * <pre>
     * ID
     * </pre>
     *
     * <code>required int32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <pre>
     * str
     * </pre>
     *
     * <code>required string str = 2;</code>
     * @return Whether the str field is set.
     */
    boolean hasStr();
    /**
     * <pre>
     * str
     * </pre>
     *
     * <code>required string str = 2;</code>
     * @return The str.
     */
    java.lang.String getStr();
    /**
     * <pre>
     * str
     * </pre>
     *
     * <code>required string str = 2;</code>
     * @return The bytes for str.
     */
    com.google.protobuf.ByteString
        getStrBytes();

    /**
     * <pre>
     *optional field
     * </pre>
     *
     * <code>optional int32 opt = 3;</code>
     * @return Whether the opt field is set.
     */
    boolean hasOpt();
    /**
     * <pre>
     *optional field
     * </pre>
     *
     * <code>optional int32 opt = 3;</code>
     * @return The opt.
     */
    int getOpt();
  }
  /**
   * Protobuf type {@code tutorial.helloworld}
   */
  public static final class helloworld extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tutorial.helloworld)
      helloworldOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use helloworld.newBuilder() to construct.
    private helloworld(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private helloworld() {
      str_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new helloworld();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private helloworld(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              str_ = bs;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              opt_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return tutorial.TutorialHelloworld.internal_static_tutorial_helloworld_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return tutorial.TutorialHelloworld.internal_static_tutorial_helloworld_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              tutorial.TutorialHelloworld.helloworld.class, tutorial.TutorialHelloworld.helloworld.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <pre>
     * ID
     * </pre>
     *
     * <code>required int32 id = 1;</code>
     * @return Whether the id field is set.
     */
    @java.lang.Override
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * ID
     * </pre>
     *
     * <code>required int32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }

    public static final int STR_FIELD_NUMBER = 2;
    private volatile java.lang.Object str_;
    /**
     * <pre>
     * str
     * </pre>
     *
     * <code>required string str = 2;</code>
     * @return Whether the str field is set.
     */
    @java.lang.Override
    public boolean hasStr() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * str
     * </pre>
     *
     * <code>required string str = 2;</code>
     * @return The str.
     */
    @java.lang.Override
    public java.lang.String getStr() {
      java.lang.Object ref = str_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          str_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     * str
     * </pre>
     *
     * <code>required string str = 2;</code>
     * @return The bytes for str.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getStrBytes() {
      java.lang.Object ref = str_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        str_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int OPT_FIELD_NUMBER = 3;
    private int opt_;
    /**
     * <pre>
     *optional field
     * </pre>
     *
     * <code>optional int32 opt = 3;</code>
     * @return Whether the opt field is set.
     */
    @java.lang.Override
    public boolean hasOpt() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     *optional field
     * </pre>
     *
     * <code>optional int32 opt = 3;</code>
     * @return The opt.
     */
    @java.lang.Override
    public int getOpt() {
      return opt_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasStr()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, str_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeInt32(3, opt_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, str_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, opt_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof tutorial.TutorialHelloworld.helloworld)) {
        return super.equals(obj);
      }
      tutorial.TutorialHelloworld.helloworld other = (tutorial.TutorialHelloworld.helloworld) obj;

      if (hasId() != other.hasId()) return false;
      if (hasId()) {
        if (getId()
            != other.getId()) return false;
      }
      if (hasStr() != other.hasStr()) return false;
      if (hasStr()) {
        if (!getStr()
            .equals(other.getStr())) return false;
      }
      if (hasOpt() != other.hasOpt()) return false;
      if (hasOpt()) {
        if (getOpt()
            != other.getOpt()) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasId()) {
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + getId();
      }
      if (hasStr()) {
        hash = (37 * hash) + STR_FIELD_NUMBER;
        hash = (53 * hash) + getStr().hashCode();
      }
      if (hasOpt()) {
        hash = (37 * hash) + OPT_FIELD_NUMBER;
        hash = (53 * hash) + getOpt();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static tutorial.TutorialHelloworld.helloworld parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tutorial.TutorialHelloworld.helloworld parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tutorial.TutorialHelloworld.helloworld parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tutorial.TutorialHelloworld.helloworld parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tutorial.TutorialHelloworld.helloworld parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tutorial.TutorialHelloworld.helloworld parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tutorial.TutorialHelloworld.helloworld parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static tutorial.TutorialHelloworld.helloworld parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static tutorial.TutorialHelloworld.helloworld parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static tutorial.TutorialHelloworld.helloworld parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static tutorial.TutorialHelloworld.helloworld parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static tutorial.TutorialHelloworld.helloworld parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(tutorial.TutorialHelloworld.helloworld prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tutorial.helloworld}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tutorial.helloworld)
        tutorial.TutorialHelloworld.helloworldOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return tutorial.TutorialHelloworld.internal_static_tutorial_helloworld_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return tutorial.TutorialHelloworld.internal_static_tutorial_helloworld_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                tutorial.TutorialHelloworld.helloworld.class, tutorial.TutorialHelloworld.helloworld.Builder.class);
      }

      // Construct using tutorial.TutorialHelloworld.helloworld.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        str_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        opt_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return tutorial.TutorialHelloworld.internal_static_tutorial_helloworld_descriptor;
      }

      @java.lang.Override
      public tutorial.TutorialHelloworld.helloworld getDefaultInstanceForType() {
        return tutorial.TutorialHelloworld.helloworld.getDefaultInstance();
      }

      @java.lang.Override
      public tutorial.TutorialHelloworld.helloworld build() {
        tutorial.TutorialHelloworld.helloworld result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public tutorial.TutorialHelloworld.helloworld buildPartial() {
        tutorial.TutorialHelloworld.helloworld result = new tutorial.TutorialHelloworld.helloworld(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.str_ = str_;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.opt_ = opt_;
          to_bitField0_ |= 0x00000004;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof tutorial.TutorialHelloworld.helloworld) {
          return mergeFrom((tutorial.TutorialHelloworld.helloworld)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(tutorial.TutorialHelloworld.helloworld other) {
        if (other == tutorial.TutorialHelloworld.helloworld.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasStr()) {
          bitField0_ |= 0x00000002;
          str_ = other.str_;
          onChanged();
        }
        if (other.hasOpt()) {
          setOpt(other.getOpt());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasId()) {
          return false;
        }
        if (!hasStr()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        tutorial.TutorialHelloworld.helloworld parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (tutorial.TutorialHelloworld.helloworld) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <pre>
       * ID
       * </pre>
       *
       * <code>required int32 id = 1;</code>
       * @return Whether the id field is set.
       */
      @java.lang.Override
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       * ID
       * </pre>
       *
       * <code>required int32 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return id_;
      }
      /**
       * <pre>
       * ID
       * </pre>
       *
       * <code>required int32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * ID
       * </pre>
       *
       * <code>required int32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object str_ = "";
      /**
       * <pre>
       * str
       * </pre>
       *
       * <code>required string str = 2;</code>
       * @return Whether the str field is set.
       */
      public boolean hasStr() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <pre>
       * str
       * </pre>
       *
       * <code>required string str = 2;</code>
       * @return The str.
       */
      public java.lang.String getStr() {
        java.lang.Object ref = str_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            str_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * str
       * </pre>
       *
       * <code>required string str = 2;</code>
       * @return The bytes for str.
       */
      public com.google.protobuf.ByteString
          getStrBytes() {
        java.lang.Object ref = str_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          str_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * str
       * </pre>
       *
       * <code>required string str = 2;</code>
       * @param value The str to set.
       * @return This builder for chaining.
       */
      public Builder setStr(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        str_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * str
       * </pre>
       *
       * <code>required string str = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearStr() {
        bitField0_ = (bitField0_ & ~0x00000002);
        str_ = getDefaultInstance().getStr();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * str
       * </pre>
       *
       * <code>required string str = 2;</code>
       * @param value The bytes for str to set.
       * @return This builder for chaining.
       */
      public Builder setStrBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        str_ = value;
        onChanged();
        return this;
      }

      private int opt_ ;
      /**
       * <pre>
       *optional field
       * </pre>
       *
       * <code>optional int32 opt = 3;</code>
       * @return Whether the opt field is set.
       */
      @java.lang.Override
      public boolean hasOpt() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <pre>
       *optional field
       * </pre>
       *
       * <code>optional int32 opt = 3;</code>
       * @return The opt.
       */
      @java.lang.Override
      public int getOpt() {
        return opt_;
      }
      /**
       * <pre>
       *optional field
       * </pre>
       *
       * <code>optional int32 opt = 3;</code>
       * @param value The opt to set.
       * @return This builder for chaining.
       */
      public Builder setOpt(int value) {
        bitField0_ |= 0x00000004;
        opt_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *optional field
       * </pre>
       *
       * <code>optional int32 opt = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearOpt() {
        bitField0_ = (bitField0_ & ~0x00000004);
        opt_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:tutorial.helloworld)
    }

    // @@protoc_insertion_point(class_scope:tutorial.helloworld)
    private static final tutorial.TutorialHelloworld.helloworld DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new tutorial.TutorialHelloworld.helloworld();
    }

    public static tutorial.TutorialHelloworld.helloworld getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<helloworld>
        PARSER = new com.google.protobuf.AbstractParser<helloworld>() {
      @java.lang.Override
      public helloworld parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new helloworld(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<helloworld> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<helloworld> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public tutorial.TutorialHelloworld.helloworld getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_helloworld_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tutorial_helloworld_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031tutorial.helloworld.proto\022\010tutorial\"2\n" +
      "\nhelloworld\022\n\n\002id\030\001 \002(\005\022\013\n\003str\030\002 \002(\t\022\013\n\003" +
      "opt\030\003 \001(\005"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_tutorial_helloworld_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tutorial_helloworld_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_helloworld_descriptor,
        new java.lang.String[] { "Id", "Str", "Opt", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
